### ISSUE TITLE
Version 0.2.0 image is not available on Docker hub

### ISSUE THREAD

**Issue by zand** [jketterl/codecserver#12]
`jketterl/openwebrx:1.2.0` will fail to load if its configured to connect to codecserver that isn't version 0.2.0 but `jketterl/codecserver:0.2.0` is not available.

I was able to clone the github repository, checkout 0.2.0, build the `codecserver:0.2.0` image, and use it locally.

**Comment by jketterl** [comment]
You are right, that step was overlooked during the release process, sorry about that. I have built the corresponding images now.

**Comment by zand** [comment]
Closing this as I see the 0.2.0 images are now available.
