### ISSUE TITLE
codecserver.pc may contain wrong include path

### ISSUE THREAD

**Issue by mweyland** [jketterl/codecserver#3]
On a debian 10.10 armhf system, building the codecserver packages from master yields a `libcodecserver-dev` with the header files installed in `/usr/include/codecserver/` and a pkgconfig file with the following content:
```
prefix=/usr
exec_prefix=/usr
libdir=${exec_prefix}/lib/arm-linux-gnueabihf
includedir=${prefix}/include

Name: codecserver
Description: 
URL: https://github.com/jketterl/owrx_connector
Version: 0.1.0

Requires: protobuf
Libs: -L${libdir} -lcodecserver
Cflags: -I${includedir}
```
However the example module includes these files without the `codecserver` prefix (see e.g. `ambe3ksession.hpp`). Thus, the pkgconfig file should either provide the full path for header includes (`/usr/include/codecserver/`), or the existing code should include header files with the `codecserver` prefix.

**Comment by jketterl** [comment]
The `ambe3k` module included with codecserver isn't really to be considered an example module. It can use the includes the way it does because it is built from the same source tree. In fact, it could not even use prefixed includes because that would require them to be installed first.
