### ISSUE TITLE
Error message on Ubuntu 21

### ISSUE THREAD

**Issue by ofadam** [jketterl/codecserver#9]
I'm getting the following when running codecserver after compiling on Ubuntu 21 – any idea where to start troubleshooting?

codecserver: symbol lookup error: codecserver: undefined symbol: _ZN11CodecServer5proto7RequestC1EPN6google8protobuf5ArenaE

**Comment by jketterl** [comment]
I cannot reproduce this. You may need to `make clean` in your build directory, or run a `sudo ldconfig`. Also check for errors during installation.
